# Generated by Django 4.1.2 on 2022-10-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_dicription',
            new_name='dep_discription',
        ),
    ]
