# Generated by Django 4.0.1 on 2022-10-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
    ]
